services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-api-prod
    env_file:
      - .local.env
    ports:
      - '8000:8000'
    depends_on:
      - exchange_prod
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    restart: unless-stopped

  exchange_prod:
    image: postgres:13
    env_file:
      - .local.env
    container_name: exchange_prod
    ports:
      - '5455:5432'
    volumes:
      - ./exchange_prod:/var/lib/postgresql/data
    restart: always
